Add Python bindings for CMSSW
fermitools/frontier pull request #41
Opened 2023-04-07 22:50 UTC by cvuosalo

Add Python bindings for CMSSW to address issue #37. The patch from https://github.com/cms-externals/frontier_client/pull/2 is included.

The following test suggested by Shahzad was completed successfully:

- #create CMSSW_13_0_X dev area
- cmsenv
- export LD_LIBRARY_PATH=/you/frontier_client/lib:${LD_LIBRARY_PATH}
- export PYTHON3PATH=/you/frontier_client/python/lib:${PYTHON3PATH}
 and run either https://github.com/cms-sw/cmssw/blob/master/CondCore/Utilities/test/test_conddb.sh or just "conddb search 4b97f78682aac6254bbcba54cedbde468202bf5b" will also test the frontier client python binding.

To confirm the test, I removed `/cvmfs/cms.cern.ch/slc7_amd64_gcc10/external/frontier_client/2.9.1-1a7a47535e14b3c7ccfb7174b32f95b4/python/lib` from the `tool-deps.pth` file usually found in `/cvmfs/cms.cern.ch/slc7_amd64_gcc10/cms/cmssw-tool-conf/52.0-ddda3f06e541677ac005e786e7381a15/lib/python3.9/site-packages/`, which ensured that the Frontier client code was coming from my new version and not from cvmfs.

2023-04-07 22:51 UTC, cvuosalo commented
@DrDaveD Please review this request.

2023-04-12 17:23 UTC, DrDaveD requested changes
I don't think the frontier.py.rej and frontier.py.orig files should be included.

2023-04-12 17:23 UTC, DrDaveD commented on client/Makefile
> +FN_VER_MINOR	=	9.2
Let's make this version 2.10.1

2023-04-12 17:23 UTC, DrDaveD commented on client/RELEASE_NOTES
> +
Don't have a blank line in here.

2023-04-14 20:02 UTC, cvuosalo commented
@DrDaveD Your requested changes have been made.

2023-04-14 20:13 UTC, DrDaveD approved these changes

2023-04-14 20:13 UTC, merged

2023-04-14 20:43 UTC, DrDaveD commented on client/Makefile
> +FN_VER_MINOR	=	9.2
Oh I guess I should have asked for 2.10.0.  Oh well, we'll skip the .0 this time.